document.writeln("<footer>");
document.writeln("<!-- 底部导航栏 -->");
document.writeln("<div class=\'footer-nav\'>");
document.writeln("  <div class=\'footer-nav-links\'>");
document.writeln("    <div class=\'links-wrapper\'>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img class=\'about-us\' src=\'./img/about-us.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name\'>关于我们</span>");
document.writeln("        <span class=\'item-english_name spaceTwo\'>about us</span>");
document.writeln("      </a>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img src=\'./img/product_service.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name distance\'>产品与服务</span>");
document.writeln("        <span class=\'item-english_name\'>Product and Service</span>");
document.writeln("      </a>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img src=\'./img/service-agreement.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name distanceTwo\'>服务协议</span>");
document.writeln("        <span class=\'item-english_name\'>Service Agreement</span>");
document.writeln("      </a>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img class=\'contact-us\' src=\'./img/contact-us.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name\'>联系我们</span>");
document.writeln("        <span class=\'item-english_name spaceOne\'>Contact Us</span>");
document.writeln("      </a>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img class=\'copyright\' src=\'./img/CopyrightStatement.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name\'>版权声明</span>");
document.writeln("        <span class=\'item-english_name spaceOne\'>Copyright </span>");
document.writeln("      </a>");
document.writeln("      <a href=\'\' class=\'links-wrapper-item\'>");
document.writeln("        <div class=\'img_wrapper\'><img src=\'./img/web-map.png\' alt=\'\'></div>");
document.writeln("        <span class=\'item-name\'>网站地图</span>");
document.writeln("        <span class=\'item-english_name\'>Website Map</span>");
document.writeln("      </a>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div class=\'footer-company_desc\'>");
document.writeln("    <div class=\'company_desc-wrapper\'>");
document.writeln("      <span class=\'desc-name\'>© 2020 深圳市比特安科技有限公司</span>");
document.writeln("      <a href='https://beian.miit.gov.cn/'><span>粤ICP备19041769号</span></a>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("</footer>");