document.writeln("");
document.writeln("  <header>");
document.writeln("    <!-- 顶部导航栏 -->");
document.writeln("    <div class=\'head-nav\'>");
document.writeln("      <!-- 导航栏商标图片 -->");
document.writeln("      <div class=\'head-nav-pic\'>");
document.writeln("        <a href=\'./index.html\'><img src=\'./img/logo.png\' alt=\'\'></a>");
document.writeln("      </div>");
document.writeln("      <!-- 具体的导航栏内容 -->");
document.writeln("      <div class=\'head-nav-links\'>");
document.writeln("        <ul>");
document.writeln("          <li class=\'links_item\'><a href=\'./index.html\'>首页</a></li>");
document.writeln("          <li class=\'links_item\'><a href=\'./solution.html\'>方案</a> </li>");
document.writeln("          <li class=\'links_item\'><a href=\'./product.html\'>产品</a></li>");
document.writeln("          <li class=\'links_item enterprise\'><a href=\'./enterprise.html\'>企业</a></li>");
document.writeln("          <li class=\'links_item\'><a href=\'./cooperation.html\'>合作</a></li>");
document.writeln(" <li class=\'links_item mall\'><a href=\'https://shop104561323.taobao.com/?spm=a230r.7195193.1997079397.216.63312727fbHeTB\' target=\'_blank\'>商城</a></li>");
document.writeln("          <li class=\'links_item platform\'><a href=\'./product_saas.html\'>充换电 <br /> 云平台</a></li>");
document.writeln("          <li class=\'links_item contactUs \'><a href=\'./contact_us.html\'>联系我们</a></li>");
document.writeln("        </ul>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </header>");
document.writeln("");
